
#figure(
  table(
    columns: (3fr, 1fr, 1fr, 1fr, 1fr, 1fr),
    align: (x, y) => if x >= 1 and y >= 1 { center + horizon } else { left },
    table.header(
      [*Article*],
      [*Holacratie*],
      [*Gouvernance distribuée*],
      [*Gestion*],
      [*Technique*],
      [*Informatique*],
    ),

    [#cite(<reinventing-organisations-frederic-laloux>, form: "full")],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [],

    [#cite(<holacracy-brian-robertson>, form: "full")], [#sym.circle.filled], [], [#sym.circle.filled], [], [],
    [#cite(<nouvelle-gouvernance-tournee-vers-la-gestion-des-risques>, form: "full")],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [],
    [],

    [#cite(<holacratic-socio-technical-system-architecture-savage>, form: "full")],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],

    [#cite(<effets-reels-systeme-holacratique>, form: "full")], [#sym.circle.filled], [], [#sym.circle.filled], [], [],
    [#cite(<holacracy-new-way-of-organizing-farkhondeh>, form: "full")],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [],
    [],

    [#cite(<holacracy-redefining-organizational-ontology-and-epistemology-robledo>, form: "full")],
    [#sym.circle.filled],
    [],
    [],
    [],
    [],

    [#cite(<holacracy-the-new-management-system>, form: "full")], [#sym.circle.filled], [], [], [], [],
    [#cite(<holacracy-modern-form-of-organizational-governance>, form: "full")],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [],
    [],

    [#cite(<holacracy-in-software-development-teams-bhandari>, form: "full")],
    [#sym.circle.filled],
    [],
    [],
    [],
    [#sym.circle.filled],

    [#cite(<how-Mercedes-addresses-digital-transformation-using-holacracy-ackermann>, form: "full")],
    [#sym.circle.filled],
    [],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],

    [#cite(<self-organization-and-Governance-in-digital-platform-ecosystems-engert>, form: "full")],
    [],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
  ),
  caption: [Thématiques abordées dans les articles initialement sélectionnés],
) <table-revue-articles-thematiques>
