= Discussion

Pour répondre à la question initiale proposée au @chap-question-recherche : "Quelles recommandations mettre en place pour concilier les impératifs d'un service informatique avec les besoins d'une gouvernance distribuée ?". Ce travail c'est intéressés à différents aspects de la gouvernance Jobtrek et de son service IT. Après avoir revu la littérature, procédé a des interviews au sein de la Fondation, organisé un atelier de réflexion sur des propositions d'améliorations, différents éléments de réponse semblent se dégager.

La revue de littérature ne semble pas faire ressortir de tensions directes entre le mode de gouvernance semi-distribué et le fonctionnement d'un service IT ou du SI. Il savère même que la présence forte de processus et de formalisme nécessaire a une gouvernance distribuée pourrait bien s'aligner avec les systèmes informatiques qui, en règle générale apprécient l'automatisation et les procédures.

Cependant, différents points d'attention sont relevés, notamment la complexité des systèmes -- les SI sont en règle générale conçus pour des fonctionnement hiérarchiques -- qui peuvent être requis pour s'accomoder d'une gouvernance dans laquelle les rôles changent et les accès sont multiples. Ou encore les défis de coordination des équipes IT avec les autres équipes, qui peut conduire a des incohérences ou l'apparition de shadow IT.

Au fil des entretiens menés avec les collaborateurs et à la suite de la phase d'évaluation, les tensions et critiques menées envers la gouvernance ne semblent pas non plus majoritaires. Le manque de communication et d'informations claires est un des principeaux reproche fait au fonctionnement actuel. Quelques éléments liés à la gouvernance sont tout de même pointés. Comme la difficulté de connaitre les limites et actions autorisées vis a vis des systèmes informatiques. Ou encore le manque de clarté si un collaborateur souhaite prendre des décisisons qui pourrainent avoir un impact sur l'informatique.

Il est aussi intéressant de noter que les tensions relevées ne semblent pas provenir de l'aspect semi distribué de notre Gouvernance mais bien des aspects distribués. Cela peut s'expliquer par le fait que la partie non distribuée de la gouvernance Jobtrek n'agit dans les fait que peu sur les aspects informatiques.

Les différents points relevés lors des entretiens correspondent bien aux potentielles contraintes que la revue de littérature soulevait pour ce type de gouvernance. Les éléments plus concrèts relevés en entretiens semblent aussi bien rentrer dans les défis de coordination et communication que peuvent rencontrer les équipes dans une gouvernance distribuée.

Comme cela à été exploré au @chap-analyse-gouvernance-jobtrek, la fondation met déjà en oeuvre une série d'éléments qui fonctionnent pour le bon fonctionnement de sa gouvernance. Notamment le Peerdom, différents meetings par cercles et rôles spécifiques. Actuellement, le travail en équipe et l'accomplissement de la mission des différents cercles de la fondation semblent apporter satisfaction. La gouvernance distribuée répond donc bien à ses objectifs pour le fonctionnement courant des cercles.

Cependant, il semble que les lacunes de la gouvernance apparaissent lorsque les processus, le cadre et les séance mise en place ne couvrent pas certains cas, en particulier lorsque des cercles transversaux doivent être impliqués, dont le cercle IT. Le cadre et les processus semblent clairs pour le fonctionnement courant des rôles dans leur cercles, il ne semble pas l'être lorsque d'autres cercles transversaux doivent intervenir au sein des cercles.

Deux niveau de réponse à la question de recherche se dégagent. En premier les actions qui peuvent être menées au niveau du fonctionnement de la gouvernance, notamment en améliorant et clarifiant certains processus ou en étendant la sphére d'autorité des rôles aux éléments informatiques -- ou d'autres selon les besoins. Cela afin d'étendre les aspects de la gouvernance qui fonctionnement bien dans les cercles produits aux cercles transversaux.

Puis, pour accompagner ces gangements globeaux de la gouvernance, des actions plus concrètes pourraient être envisagées pour améliorer le fonctionnement sur le terrain des services fournis par le cercle informatique.

Parmis les différentes mesures d'amélioration explorées dans ce rapoort, certaines se placent au niveau de la gouvernance, d'autres au niveaux du fonctionnement concrèt de l'informatique. Aucunne mesure ne ressort comme étant particulièrement prérequise à la mise en place des suivantes. Cela indique qu'il est possible de travailler au niveau gouvernance tout comme au niveau fonctionnement de l'informatique en parallèle. Les apports dans chaque dommaine devraient aussi avoir des impacts positifs dans l'autre. Typiquemment l'amélioration de la structuration des fichiers et une gestion d'accès cohérente à ces dérniers est une mesure très concrète sur le fonctionnement IT, mais aurait sans doute des impacts importants sur la gouvernance. Notamment en simlifiant le travail inter cercles, en uniformisant les pratiques ou en renforcant la mutualisation de certaines ressources.

== Proposition de stratégie d'implémentation
