// Propositions d'améliorations lors des entretiens

#import "kano_functions.typ": category_cell

#figure(
  table(
    columns: (0.5fr, 1.8fr, 2fr, 2fr, 2fr, 2fr, 2fr),
    inset: (0.4em, 0.6em),
    align: horizon + center,
    [],
    table.cell(colspan: 6)[*Mesure absente*],
    [], [], [*ça me plait*], [*normal*], [*égal*], [*contentement*], [*déplait*],
    table.cell(rowspan: 5, rotate(-90deg, reflow: true)[*Mesure présente*]),
    [*ça me plait*],
    category_cell("questionable"),
    category_cell("attractive"),
    category_cell("attractive"),
    category_cell("attractive"),
    category_cell("performance"),
    [*normal*],
    category_cell("reverse"),
    category_cell("questionable"),
    category_cell("indiferent"),
    category_cell("indiferent"),
    category_cell("must-be"),
    [*égal*],
    category_cell("reverse"),
    category_cell("indiferent"),
    category_cell("indiferent"),
    category_cell("indiferent"),
    category_cell("must-be"),
    [*contentement*],
    category_cell("reverse"),
    category_cell("indiferent"),
    category_cell("indiferent"),
    category_cell("questionable"),
    category_cell("must-be"),
    [*déplait*],
    category_cell("reverse"),
    category_cell("reverse"),
    category_cell("reverse"),
    category_cell("reverse"),
    category_cell("questionable"),
  ),
  caption: [Matrice de knao],
) <table-kano-matrix>
