// Propositions d'améliorations l'ors des entretiens

#figure(
  table(
    columns: (1fr, 60%, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr),
    align: horizon + left,
    table.header(
      [],
      [*Mesure proposée par l'interviewé*],
      [*P1*],
      [*P2*],
      [*P3*],
      [*P4*],
      [*P5*],
      [*P6*],
    ),

    [*M1* <test>],
    [Simplification et uniformisation de l'architecture d'accès aux fichiers. Retirer les doublonset y intégrer une partie commune a tous les cercles.],
    [#sym.circle.filled],
    [],
    [],
    [#sym.circle.filled],
    [],
    [],

    [*M2*],
    [Outil de prise de décision en autonomie sur la sécurité des données. Protocole personnel de traitement de ces dérnières, d'anonymisation, de suppression. (pour les rôles et les cercles)],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [],

    [*M3*],
    [Documentation/base de connaissances interne co-construite (processus, recommandations, liste des outils, astuces, FAQ).],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],

    [*M4*],
    [E-learning avec modules de formation qui peuvent être suivi par les collaborateurs en tous temps. Y intégrer des quizz.],
    [],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],

    [*M5*],
    [Proposer un cadre d'utilisation des outils numériques clair et justifié (sphère d'autorité des rôles).],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],

    [*M6*],
    [Possibilité de soumettre des demandes de modification du cadre (via le mécanisme actuel de gestion des tensions, revoir ce dérnier).],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [],
    [#sym.circle.filled],
    [],

    [*M7*], [Mise en place d'un facilitateur "sécurité", un équivalent DPO.], [], [#sym.circle.filled], [], [], [], [],
    [*M8*],
    [Structure du Peerdom qui permette aux collaborateurs de savoir efficacement qui contacter pour quelle demande (simplification des rôles).],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [],
    [],

    [*M9*],
    [Mécanisme de newsletter IT. Qui informerait des changements à venir, donnerait les liens vers les tutos ou la documentation.],
    [#sym.circle.filled],
    [],
    [],
    [],
    [],
    [#sym.circle.filled],

    [*M10*],
    [Point sur l'IT et la sécurité lors des réunions trimestrielles. Bonnes pratiques, rappel sécurité ciblés, astuces.],
    [],
    [],
    [#sym.circle.filled],
    [],
    [],
    [#sym.circle.filled],

    [*M11*],
    [Uniformiser les outils de travail entre les cercles et limiter leur nombre, communiquer lequel sert a quoi.],
    [#sym.circle.filled],
    [],
    [],
    [#sym.circle.filled],
    [],
    [],

    [*M12*],
    [Processus d'onboarding plus complet, avec formation a visualiser en avance.],
    [],
    [],
    [],
    [#sym.circle.filled],
    [],
    [],

    [*M13*],
    [Support qui fourni une estimation du temps de résolution, et qui informe en cas d'évolution.],
    [],
    [],
    [],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],

    [*M14*],
    [Favoriser l'innovation en poussant les collaborateurs à partager leurs bonnes pratiques et à proposer de nouveaux outils.],
    [],
    [],
    [],
    [],
    [#sym.circle.filled],
    [],

    [*M15*],
    [Définir un process lorsque l'IT met en place de nouveaux éléments qui vont impacter les cercles (informer, présenter, justifier, planifier).],
    [],
    [],
    [],
    [],
    [],
    [#sym.circle.filled],

    [*M16*],
    [Règles plus claires pour l'utilisation du matériel IT partagé, notamment les postes de travail.],
    [],
    [],
    [],
    [],
    [],
    [#sym.circle.filled],

    [*M17*],
    [Adopter une stratégie qui pérénise et stabilise l'actuel avant d'impliquer de nouveaux outils. Echelonner les changements et permettre aux collaborateurs de se projetter.],
    [],
    [],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
  ),
  caption: [Fréquence d'apparition des mesures d'améliorations proposées par les interviewées.],
) <table-propositions-mesures>
