// Propositions d'améliorations l'ors des entretiens

#figure(
  table(
    columns: (2fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr, 1fr),
    align: (x, y) => if x > 1 { center } else { left } + horizon,
    table.header(
      [*Mesure*],
      [#link(<t1>)[*T1*]],
      [#link(<t2>)[*T2*]],
      [#link(<t3>)[*T3*]],
      [#link(<t4>)[*T4*]],
      [#link(<t5>)[*T5*]],
      [#link(<t6>)[*T6*]],
      [#link(<t7>)[*T7*]],
      [#link(<t8>)[*T8*]],
      [#link(<t9>)[*T9*]],
      [#link(<t10>)[*T10*]],
      [#link(<t11>)[*T11*]],
    ),

    [#link(<mesure-M3>)[*M3*]],
    [#sym.circle.filled],
    [],
    [],
    [#sym.circle.filled],
    [],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [],
    [],

    [#link(<mesure-M2>)[*M2*]],
    [],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [],
    [],
    [],
    [#sym.circle.filled],
    [],
    [],
    [],

    [#link(<mesure-M5>)[*M5*]],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [#sym.circle.filled],
    [],
    [#sym.circle.filled],
    [],
    [],
    [],
    [],
  ),
  caption: [Quelles mesures répondent à quelles tensions.],
) <table-mesures-tensions>
